#!/usr/bin/env python3
"""
create_video.py - Cross-platform Python script to compile stacked images into video

This script uses ffmpeg to create a video from a sequence of stacked images
generated by imgstax. It works on Windows, macOS, and Linux.

Requirements:
    - Python 3.6+
    - ffmpeg installed and in PATH
"""

import sys
import argparse
import subprocess
import shutil
from pathlib import Path
from typing import List, Optional, Tuple
import re


class Colors:
    """ANSI color codes for terminal output."""
    BLUE = '\033[0;34m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    NC = '\033[0m'  # No Color

    @staticmethod
    def is_supported():
        """Check if terminal supports colors."""
        return sys.platform != 'win32' or 'ANSICON' in os.environ


def print_info(message: str) -> None:
    """Print info message."""
    if Colors.is_supported():
        print(f"{Colors.BLUE}[INFO]{Colors.NC} {message}")
    else:
        print(f"[INFO] {message}")


def print_success(message: str) -> None:
    """Print success message."""
    if Colors.is_supported():
        print(f"{Colors.GREEN}[SUCCESS]{Colors.NC} {message}")
    else:
        print(f"[SUCCESS] {message}")


def print_warning(message: str) -> None:
    """Print warning message."""
    if Colors.is_supported():
        print(f"{Colors.YELLOW}[WARNING]{Colors.NC} {message}")
    else:
        print(f"[WARNING] {message}")


def print_error(message: str) -> None:
    """Print error message."""
    if Colors.is_supported():
        print(f"{Colors.RED}[ERROR]{Colors.NC} {message}")
    else:
        print(f"[ERROR] {message}")


def check_ffmpeg() -> bool:
    """Check if ffmpeg is installed and accessible.

    Returns:
        True if ffmpeg is available, False otherwise
    """
    ffmpeg_path = shutil.which('ffmpeg')
    if not ffmpeg_path:
        print_error("ffmpeg is not installed or not in PATH")
        print()
        print("Installation instructions:")
        print("  macOS:   brew install ffmpeg")
        print("  Ubuntu:  sudo apt-get install ffmpeg")
        print("  Windows: Download from https://ffmpeg.org/download.html")
        print()
        return False

    try:
        result = subprocess.run(
            ['ffmpeg', '-version'],
            capture_output=True,
            text=True,
            check=False
        )
        version_line = result.stdout.split('\n')[0]
        print_info(f"ffmpeg found: {version_line}")
        return True
    except Exception as e:
        print_error(f"Error checking ffmpeg: {e}")
        return False


def find_images(input_dir: Path, pattern: str = 'stacked-*.*') -> List[Path]:
    """Find all image files in the directory, excluding metadata.json.

    Args:
        input_dir: Directory to search for images
        pattern: Glob pattern for matching files

    Returns:
        Sorted list of image paths

    Raises:
        ValueError: If no images are found
    """
    print_info(f"Searching for images in: {input_dir}")

    extensions = {'.jpg', '.jpeg', '.png', '.tif', '.tiff'}
    images = []

    for file_path in input_dir.iterdir():
        if (file_path.is_file() and
            file_path.suffix.lower() in extensions and
            file_path.name != 'metadata.json'):
            images.append(file_path)

    if not images:
        raise ValueError(f"No images found in {input_dir}")

    images.sort()
    print_success(f"Found {len(images)} images")
    return images


def determine_input_pattern(images: List[Path]) -> Optional[str]:
    """Determine the ffmpeg input pattern from the image list.

    Args:
        images: List of sorted image paths

    Returns:
        Input pattern string for ffmpeg, or None if pattern cannot be determined
    """
    if not images:
        return None

    first_image = images[0]
    basename = first_image.name

    # Match pattern like "stacked-00001.jpg"
    match = re.match(r'^(.*?)(\d+)(\.[^.]+)$', basename)
    if not match:
        return None

    prefix, number, ext = match.groups()
    num_digits = len(number)

    # Create pattern like "stacked-%05d.jpg"
    pattern = f"{prefix}%0{num_digits}d{ext}"
    return str(first_image.parent / pattern)


def get_codec_args(codec: str, quality: str) -> List[str]:
    """Get ffmpeg codec-specific arguments.

    Args:
        codec: Codec name (libx264, libx265, libvpx-vp9, prores)
        quality: Quality preset (low, medium, high, lossless)

    Returns:
        List of ffmpeg arguments for the codec and quality
    """
    args = []

    if codec == 'libx264':
        args.extend(['-c:v', 'libx264'])
        if quality == 'low':
            args.extend(['-preset', 'fast', '-crf', '28'])
        elif quality == 'medium':
            args.extend(['-preset', 'medium', '-crf', '23'])
        elif quality == 'high':
            args.extend(['-preset', 'slow', '-crf', '18'])
        elif quality == 'lossless':
            args.extend(['-preset', 'veryslow', '-crf', '0'])
        args.extend(['-pix_fmt', 'yuv420p'])

    elif codec == 'libx265':
        args.extend(['-c:v', 'libx265'])
        if quality == 'low':
            args.extend(['-preset', 'fast', '-crf', '32'])
        elif quality == 'medium':
            args.extend(['-preset', 'medium', '-crf', '28'])
        elif quality == 'high':
            args.extend(['-preset', 'slow', '-crf', '22'])
        elif quality == 'lossless':
            args.extend(['-preset', 'veryslow', '-x265-params', 'lossless=1'])
        args.extend(['-pix_fmt', 'yuv420p'])

    elif codec == 'libvpx-vp9':
        args.extend(['-c:v', 'libvpx-vp9'])
        if quality == 'low':
            args.extend(['-b:v', '1M', '-crf', '40'])
        elif quality == 'medium':
            args.extend(['-b:v', '2M', '-crf', '31'])
        elif quality == 'high':
            args.extend(['-b:v', '4M', '-crf', '22'])
        elif quality == 'lossless':
            args.extend(['-lossless', '1'])

    elif codec == 'prores':
        args.extend(['-c:v', 'prores_ks', '-profile:v', '3'])

    return args


def create_video(
    input_dir: Path,
    output_file: Path,
    fps: int = 30,
    codec: str = 'libx264',
    quality: str = 'high',
    scale: Optional[str] = None,
    force: bool = False
) -> bool:
    """Create video from stacked images using ffmpeg.

    Args:
        input_dir: Directory containing stacked images
        output_file: Output video file path
        fps: Frames per second
        codec: Video codec to use
        quality: Quality preset
        scale: Optional scale parameter (e.g., "1920x1080", "-1:720")
        force: Skip confirmation prompt

    Returns:
        True if successful, False otherwise
    """
    # Check ffmpeg
    if not check_ffmpeg():
        return False

    # Find images
    try:
        images = find_images(input_dir)
    except ValueError as e:
        print_error(str(e))
        return False

    # Determine input pattern
    input_pattern = determine_input_pattern(images)
    if not input_pattern:
        print_error("Could not determine image numbering pattern")
        return False

    # Auto-detect codec from output extension
    output_ext = output_file.suffix.lower()
    if codec == 'libx264':
        if output_ext == '.webm':
            codec = 'libvpx-vp9'
            print_info("Detected WebM format, using VP9 codec")
        elif output_ext == '.mov':
            codec = 'prores'
            print_info("Detected MOV format, using ProRes codec")

    # Build ffmpeg command
    ffmpeg_cmd = [
        'ffmpeg', '-y',
        '-framerate', str(fps),
        '-i', input_pattern
    ]

    # Add codec-specific arguments
    ffmpeg_cmd.extend(get_codec_args(codec, quality))

    # Add scaling if specified
    if scale:
        ffmpeg_cmd.extend(['-vf', f'scale={scale}'])

    # Add output file
    ffmpeg_cmd.append(str(output_file))

    # Display settings
    print()
    print_info("=== Video Creation Settings ===")
    print(f"  Input directory: {input_dir}")
    print(f"  Output file:     {output_file}")
    print(f"  Images found:    {len(images)}")
    print(f"  Frame rate:      {fps} fps")
    print(f"  Codec:           {codec}")
    print(f"  Quality:         {quality}")
    if scale:
        print(f"  Scale:           {scale}")
    print()

    # Calculate video duration
    duration = len(images) / fps
    print_info(f"Estimated video duration: {duration:.2f}s")
    print()

    # Ask for confirmation
    if not force:
        try:
            response = input("Proceed with video creation? [Y/n] ")
            if response and response.lower() not in ('y', 'yes'):
                print_warning("Cancelled by user")
                return False
        except (KeyboardInterrupt, EOFError):
            print()
            print_warning("Cancelled by user")
            return False

    # Execute ffmpeg
    print_info("Creating video...")
    print()

    try:
        result = subprocess.run(ffmpeg_cmd, check=False)

        if result.returncode == 0:
            print()
            print_success(f"Video created successfully: {output_file}")

            # Display file size
            if output_file.exists():
                file_size = output_file.stat().st_size
                file_size_mb = file_size / (1024 * 1024)
                print_info(f"File size: {file_size_mb:.2f} MB")

            return True
        else:
            print_error("Video creation failed")
            return False

    except Exception as e:
        print_error(f"Error running ffmpeg: {e}")
        return False


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Compile stacked images into a video using ffmpeg',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s output_directory
  %(prog)s output_directory -o timelapse.mp4 -f 60
  %(prog)s output_directory -c libx265 -q high
  %(prog)s output_directory -s -1:720
  %(prog)s output_directory -o video.webm -c libvpx-vp9

Requirements:
  ffmpeg must be installed and in PATH
        """
    )

    parser.add_argument(
        'input_directory',
        type=Path,
        help='Directory containing stacked images'
    )

    parser.add_argument(
        '-o', '--output',
        type=Path,
        help='Output video file (default: output_<timestamp>.mp4)'
    )

    parser.add_argument(
        '-f', '--fps',
        type=int,
        default=30,
        help='Frames per second (default: 30)'
    )

    parser.add_argument(
        '-c', '--codec',
        choices=['libx264', 'libx265', 'libvpx-vp9', 'prores'],
        default='libx264',
        help='Video codec (default: libx264)'
    )

    parser.add_argument(
        '-q', '--quality',
        choices=['low', 'medium', 'high', 'lossless'],
        default='high',
        help='Quality preset (default: high)'
    )

    parser.add_argument(
        '-s', '--scale',
        help='Scale video (e.g., "1920x1080", "-1:720")'
    )

    parser.add_argument(
        '--force',
        action='store_true',
        help='Skip confirmation prompt'
    )

    args = parser.parse_args()

    # Validate input directory
    if not args.input_directory.exists():
        print_error(f"Input directory does not exist: {args.input_directory}")
        return 1

    if not args.input_directory.is_dir():
        print_error(f"Input path is not a directory: {args.input_directory}")
        return 1

    # Determine output file
    if not args.output:
        from datetime import datetime
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        args.output = Path(f'output_{timestamp}.mp4')

    # Create video
    success = create_video(
        input_dir=args.input_directory,
        output_file=args.output,
        fps=args.fps,
        codec=args.codec,
        quality=args.quality,
        scale=args.scale,
        force=args.force
    )

    return 0 if success else 1


if __name__ == '__main__':
    sys.exit(main())
