#Requires -Version 5.0
<#
.SYNOPSIS
    Compile stacked images into a video using ffmpeg (PowerShell)

.DESCRIPTION
    This script uses ffmpeg to create a video from a sequence of stacked images
    generated by imgstax. It automatically excludes metadata.json and provides
    various quality and codec options.

.PARAMETER InputDirectory
    Directory containing the stacked images (required)

.PARAMETER OutputFile
    Output video filename (default: output_<timestamp>.mp4)

.PARAMETER Fps
    Frames per second (default: 30)

.PARAMETER Codec
    Video codec to use (default: libx264)
    Options: libx264, libx265, libvpx-vp9, prores

.PARAMETER Quality
    Quality preset (default: high)
    Options: low, medium, high, lossless

.PARAMETER Pattern
    Image filename pattern (default: stacked-*.*)

.PARAMETER Scale
    Scale video resolution (e.g., "1920x1080", "-1:720")

.EXAMPLE
    .\create_video.ps1 -InputDirectory "output_directory"

.EXAMPLE
    .\create_video.ps1 -InputDirectory "output" -OutputFile "timelapse.mp4" -Fps 60 -Quality high

.EXAMPLE
    .\create_video.ps1 -InputDirectory "output" -Codec libx265 -Scale "-1:720"

.NOTES
    Requirements: ffmpeg must be installed and in PATH
    Download from: https://ffmpeg.org/download.html
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$InputDirectory,

    [Parameter(Mandatory=$false)]
    [string]$OutputFile = "",

    [Parameter(Mandatory=$false)]
    [int]$Fps = 30,

    [Parameter(Mandatory=$false)]
    [ValidateSet('libx264', 'libx265', 'libvpx-vp9', 'prores')]
    [string]$Codec = 'libx264',

    [Parameter(Mandatory=$false)]
    [ValidateSet('low', 'medium', 'high', 'lossless')]
    [string]$Quality = 'high',

    [Parameter(Mandatory=$false)]
    [string]$Pattern = 'stacked-*.*',

    [Parameter(Mandatory=$false)]
    [string]$Scale = "",

    [Parameter(Mandatory=$false)]
    [switch]$Force
)

# Color output functions
function Write-InfoMessage {
    param([string]$Message)
    Write-Host "[INFO] " -ForegroundColor Blue -NoNewline
    Write-Host $Message
}

function Write-SuccessMessage {
    param([string]$Message)
    Write-Host "[SUCCESS] " -ForegroundColor Green -NoNewline
    Write-Host $Message
}

function Write-WarningMessage {
    param([string]$Message)
    Write-Host "[WARNING] " -ForegroundColor Yellow -NoNewline
    Write-Host $Message
}

function Write-ErrorMessage {
    param([string]$Message)
    Write-Host "[ERROR] " -ForegroundColor Red -NoNewline
    Write-Host $Message
}

# Check if ffmpeg is installed
function Test-FFmpeg {
    try {
        $ffmpegVersion = & ffmpeg -version 2>&1 | Select-Object -First 1
        Write-InfoMessage "ffmpeg found: $ffmpegVersion"
        return $true
    }
    catch {
        Write-ErrorMessage "ffmpeg is not installed or not in PATH"
        Write-Host ""
        Write-Host "Download ffmpeg from: https://ffmpeg.org/download.html"
        Write-Host "After installing, add ffmpeg to your PATH environment variable"
        Write-Host ""
        return $false
    }
}

# Main script
try {
    # Validate input directory
    if (-not (Test-Path -Path $InputDirectory -PathType Container)) {
        Write-ErrorMessage "Input directory does not exist: $InputDirectory"
        exit 1
    }

    # Check for ffmpeg
    if (-not (Test-FFmpeg)) {
        exit 1
    }

    # Find images (excluding metadata.json)
    Write-InfoMessage "Searching for images in: $InputDirectory"
    $images = Get-ChildItem -Path $InputDirectory -File | Where-Object {
        $_.Extension -match '\.(jpg|jpeg|png|tif|tiff)$' -and
        $_.Name -ne 'metadata.json'
    } | Sort-Object Name

    $imageCount = $images.Count

    if ($imageCount -eq 0) {
        Write-ErrorMessage "No images found in $InputDirectory"
        exit 1
    }

    Write-SuccessMessage "Found $imageCount images"

    # Determine output file
    if ([string]::IsNullOrEmpty($OutputFile)) {
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $OutputFile = "output_$timestamp.mp4"
    }

    # Get output extension
    $outputExt = [System.IO.Path]::GetExtension($OutputFile).TrimStart('.')

    # Adjust codec based on output extension if default
    if ($Codec -eq 'libx264') {
        switch ($outputExt) {
            'webm' {
                $Codec = 'libvpx-vp9'
                Write-InfoMessage "Detected WebM format, using VP9 codec"
            }
            'mov' {
                $Codec = 'prores'
                Write-InfoMessage "Detected MOV format, using ProRes codec"
            }
        }
    }

    # Find first image to determine pattern
    $firstImage = $images[0]
    if (-not $firstImage) {
        Write-ErrorMessage "Could not find first image"
        exit 1
    }

    # Determine input pattern for ffmpeg
    $basename = $firstImage.Name
    if ($basename -match '^(.*?)(\d+)(\.[^.]+)$') {
        $prefix = $Matches[1]
        $number = $Matches[2]
        $ext = $Matches[3]
        $numDigits = $number.Length

        # Create pattern like "stacked-%05d.jpg"
        $inputPattern = Join-Path $InputDirectory "${prefix}%0${numDigits}d${ext}"
    }
    else {
        Write-ErrorMessage "Could not determine image numbering pattern"
        exit 1
    }

    # Build ffmpeg arguments
    $ffmpegArgs = @('-y', '-framerate', $Fps, '-i', $inputPattern)

    # Codec-specific settings
    switch ($Codec) {
        'libx264' {
            $ffmpegArgs += '-c:v', 'libx264'
            switch ($Quality) {
                'low'      { $ffmpegArgs += '-preset', 'fast', '-crf', '28' }
                'medium'   { $ffmpegArgs += '-preset', 'medium', '-crf', '23' }
                'high'     { $ffmpegArgs += '-preset', 'slow', '-crf', '18' }
                'lossless' { $ffmpegArgs += '-preset', 'veryslow', '-crf', '0' }
            }
            $ffmpegArgs += '-pix_fmt', 'yuv420p'
        }

        'libx265' {
            $ffmpegArgs += '-c:v', 'libx265'
            switch ($Quality) {
                'low'      { $ffmpegArgs += '-preset', 'fast', '-crf', '32' }
                'medium'   { $ffmpegArgs += '-preset', 'medium', '-crf', '28' }
                'high'     { $ffmpegArgs += '-preset', 'slow', '-crf', '22' }
                'lossless' { $ffmpegArgs += '-preset', 'veryslow', '-x265-params', 'lossless=1' }
            }
            $ffmpegArgs += '-pix_fmt', 'yuv420p'
        }

        'libvpx-vp9' {
            $ffmpegArgs += '-c:v', 'libvpx-vp9'
            switch ($Quality) {
                'low'      { $ffmpegArgs += '-b:v', '1M', '-crf', '40' }
                'medium'   { $ffmpegArgs += '-b:v', '2M', '-crf', '31' }
                'high'     { $ffmpegArgs += '-b:v', '4M', '-crf', '22' }
                'lossless' { $ffmpegArgs += '-lossless', '1' }
            }
        }

        'prores' {
            $ffmpegArgs += '-c:v', 'prores_ks', '-profile:v', '3'
        }
    }

    # Add scaling if specified
    if (-not [string]::IsNullOrEmpty($Scale)) {
        $ffmpegArgs += '-vf', "scale=$Scale"
    }

    # Add output file
    $ffmpegArgs += $OutputFile

    # Display settings
    Write-Host ""
    Write-InfoMessage "=== Video Creation Settings ==="
    Write-Host "  Input directory: $InputDirectory"
    Write-Host "  Output file:     $OutputFile"
    Write-Host "  Images found:    $imageCount"
    Write-Host "  Frame rate:      $Fps fps"
    Write-Host "  Codec:           $Codec"
    Write-Host "  Quality:         $Quality"
    if (-not [string]::IsNullOrEmpty($Scale)) {
        Write-Host "  Scale:           $Scale"
    }
    Write-Host ""

    # Calculate video duration
    $duration = [math]::Round($imageCount / $Fps, 2)
    Write-InfoMessage "Estimated video duration: ${duration}s"
    Write-Host ""

    # Ask for confirmation
    if (-not $Force) {
        $response = Read-Host "Proceed with video creation? [Y/n]"
        if ($response -and $response -notmatch '^[Yy]') {
            Write-WarningMessage "Cancelled by user"
            exit 0
        }
    }

    # Execute ffmpeg
    Write-InfoMessage "Creating video..."
    Write-Host ""

    & ffmpeg $ffmpegArgs

    if ($LASTEXITCODE -eq 0) {
        Write-Host ""
        Write-SuccessMessage "Video created successfully: $OutputFile"

        # Display file size
        if (Test-Path -Path $OutputFile) {
            $fileSize = (Get-Item $OutputFile).Length
            $fileSizeMB = [math]::Round($fileSize / 1MB, 2)
            Write-InfoMessage "File size: $fileSizeMB MB"
        }
    }
    else {
        Write-ErrorMessage "Video creation failed"
        exit 1
    }
}
catch {
    Write-ErrorMessage "An error occurred: $_"
    exit 1
}
